name: speedtest
on:
  workflow_dispatch:
  
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: |
            apt install speedtest-cli
            speedtest -u
  
