name: speedtest
on:
  workflow_dispatch:
  
jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.13.0-alpha.5'
      - run: |
            sudo apt-get update
            sudo apt install speedtest-cli
            cd YouTubeDownload
            speedtest -u
  
