name: 人民日报
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '00 10 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.13.0-alpha.5'
      - run: pip install requests
      - run: pip install PyPDF2
      - run: python .github/workflows/人民日报.py
      - run: git config --global user.name "yiyifred"
      - run: git config --global user.email "124337092+yiyifred@users.noreply.github.com"
      - run: ssh-keygen -t rsa -C "yiyifred@qq.com"
        env:
          KEY: ${{secrets.KEY}}
      - run: echo "$KEY" >> ./.ssh/id_rsa
      - run: echo "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABgQDUMk0nRbeJTrqPkX+mSh384yW4L/GISqUJbbmCjIutrv+YxfK4SoKznLYqikg9o7YHA8v9axba/RVxLZoSgSSkMrwvWbJQ5LJeTf5WliIB7yWaP48LBvaFJJCL4bPYe2kIKf78Zio9Iwwsi1gjtJ1600ms53E+xmZp7o4n/jMN50M/bpYnhk1Sc0YynsJw8sUI0M3W608c4MehBxs+I7ciJfz98RojaunPZO4iSUHvuDiuFkQsmk8cebRyys9J4o+dHdMVZJ2ApTaDfhDbe2yyRsNBdcdhS9yr4CSxwQ4Z/cTXUtOTED1fc2dSeGKi7bTLzHKG4p81LGxvqQNSfGvT7/p/ERyvupYRPGEAzEGe/fihrArWPkPxz9bopVhBIzfQ+wd099ni2utzBUlrVWgrnrH+D1ofZF8ZJWAQadOJRu8WItiyPNOenZixmn8+fJeqXUqBlE4OPsbJ+OL173CdPlQVcBS+XphyUGicvBwb5waeA7iWkagGSDN76tBxU8c= yiyifred@qq.com" >> ./.ssh/id_rsa.pub
      - run: git remote set-url origin git@github.com:yiyifred/test.git
      - run: git add 人民日报下载目录/
      - run: git status -s
      - run: git commit -m "1"
      - run: git push -u origin main 
