name: 人民日报
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '00 10 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.13.0-alpha.5'
      - run: pip install requests
      - run: pip install PyPDF2
      - run: python .github/workflows/人民日报.py
      - run: git config --global user.name "yiyifred"
      - run: git config --global user.email "124337092+yiyifred@users.noreply.github.com"
      #- run: ssh-keygen -t rsa -f "/home/runner/.ssh/id_rsa" -C "yiyifred@qq.com"
      #  env:
      #    KEY: ${{secrets.KEY}}
      #- run: rm /home/runner/.ssh/id_rsa
      #- run: echo $KEY >> /home/runner/.ssh/id_rsa
      #- run: ssh -T git@github.com
      #- run: git remote set-url origin git@github.com:yiyifred/test.git
      - run: git add 人民日报下载目录/
      - run: git status -s
      #- run: git commit -m "1"
      #- run: git push -u origin main 
      - uses: actions/checkout@v4
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal access token.
          fetch-depth: 0 # otherwise, there would be errors pushing refs to the destination repository.
      - name: Commit files
        run: |
          git commit -m "1"
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          branch: ${{ github.ref }}
