name: wxpusher
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '00 11 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.13.0-alpha.5'
      - run: |
             pip install requests
             pip install chinese_calendar
      - run: python .github/workflows/test.py
