name: 人民日报
on:
  workflow_dispatch:
  schedule:
    # IMPORTANT: Set cron job in UTC timezone
    - cron:  '00 10 * * *'

jobs:
  run-python-script:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v2
        with:
          python-version: '3.13.0-alpha.5'
      - run: |
          pip install requests
          pip install PyPDF2
          python .github/workflows/人民日报.py
          git config --global user.name "yiyifred"
          git config --global user.email "124337092+yiyifred@users.noreply.github.com"
          mkdir .ssh
          echo "${{secrets.KEY}}" >> ./.ssh/id_rsa
          git remote set-url origin git@github.com:yiyifred/test.git
          git add 人民日报下载目录/
          git status -s
          git commit -m "1"
          git push -u origin main 
